### PR TITLE
bugfix does not call onFinish on Init

### PR DESCRIPTION
**Pull request by CupIvan**
when slider inits in hidden div and than div will show there was no any event onFinished/onChanged

### CODE REVIEW

**Comment by CupIvan** [comment]
so, when slider init in hidden div: this.$cache.rs.outerWidth(false) is undefined

**Comment by IonDen** [comment]
Hello, thanks for your PR. I will check it soon.

**Comment by jorrit** [comment]
This should have been a semver minor change because behavior was changed.

**Comment by IonDen** [comment]
@jorrit, thanks for mention, i missed that. Will try not to make same mistake in future

**Comment by ntzm** [comment]
Any update on the revert? Really annoying how we can't update to the latest version

**Comment by IonDen** [comment]
Reverted in 2.1.7

**Pull request merged**
