### PR TITLE
Added a decorator function

### PR DESCRIPTION
**Pull request by vedant1811**
One can use the decorator function for more control over decorating the display of values of the slider. Like, with an input of height in inches, one can display feet and inches:

        decorator: function(num) {
            var feet = Math.floor(num / 12);
            var inches = num % 12;
            return feet + "'" + inches + '"'; // output something like 6"7'
        }

### CODE REVIEW

**Comment by IonDen** [comment]
@vedant1811, hello. Slider already have it's own decorator function. It is called prettify. Check this demo with your example: http://jsfiddle.net/IonDen/kLb2r4qe/

**Comment by vedant1811** [comment]
@IonDen oh thank-you. I didn't realize. Maybe add this to the README?

**Comment by IonDen** [comment]
@vedant1811, it is in readme. Also, there are several demos on website with it.

**Comment by vedant1811** [comment]
oops

**Pull request closed without merging**
