### PR TITLE
New modern square design

### PR DESCRIPTION
**Pull request by grimalschi**
One more good skin.

square

Demo: http://jsfiddle.net/4td8Lu6y/4/

let me now if there is something to fix in code, please.

### CODE REVIEW

**Comment by IonDen** [comment]
Hi, looking very good. Could you make labels squared also? I think they have some border radius now.

**Comment by grimalschi** [comment]
Could you add them also to website?

**Comment by grimalschi** [comment]
Fixed same css conflict as here: https://github.com/IonDen/ion.rangeSlider/pull/539

**Comment by grimalschi** [comment]
Sorry, one more fix.

Missed style for .irs-bar-edge, so before:


And after:

**Comment by IonDen** [comment]
I will add this to website soon.

**Comment by grimalschi** [comment]
Any news?

**Comment by IonDen** [comment]
Hi, sorry that it takes a long time, but soon :)

**Comment by grimalschi** [comment]
Great! Thank you :)

**Pull request merged**
