### PR TITLE
Over Limit & Drag curosr

### PR DESCRIPTION
**Pull request by Gianpy86**
Hi,

I just added the cursor "move" when dragable and the config to go over limit when double

### CODE REVIEW

**Comment by IonDen** [comment]
HI, i am not really sure, why should plugin need this. Please provide a detailed demo.

**Comment by Gianpy86** [comment]
Hi,
in attachment the prohect with a html demo.
As u can see there, with this parameter you can exceed the other date and
it'll be the same as u picked.
For example:
if you have form set to 1st of jan 2014 and to set to 1st jan 2015 and you
want to move from 1st jan 2016 to 1st feb 2016 without over limit u cant,
with over limit you can get the from tick and move over the "to" tick and
moving that too.

I'm so sorry for my bad english,
hope it is clear but please ask me if not
Regards
John


Il giorno dom 31 mag 2015 alle ore 13:29 Denis Ineshin <
notifications@github.com> ha scritto:

**Comment by IonDen** [comment]
I mean the demo should be online on jsfiddle: http://jsfiddle.net/IonDen/y81j67qh/
Replace original url to plugin and paste your demo.

**Comment by Gianpy86** [comment]
Sorry,

hope this is what you ask me.

http://jsfiddle.net/94gwsfe9/2/

feel free to ask me

Regards
John

Il giorno lun 1 giu 2015 alle ore 06:34 Denis Ineshin <
notifications@github.com> ha scritto:

**Comment by IonDen** [comment]
Hello, ok. I checked this. Maybe i will add this feature in future, but your PR is too messy and out of code style to be merged in to project.

But, nether the less, thank you very much for this interesting feature.
I created 2 tickets to do this: #301, #302

**Pull request closed without merging**
