### PR TITLE
Buf fix (Issue: #186, #192)

### PR DESCRIPTION
**Pull request by FiloSpaTeam**
I've tried only one way to solve this problem.
Like i thinked the slider redraw itself even when is not displayed and the HTML display none is very heavy.
So i added 2 parameters, 1 is optional, the other no:
* display_parent : The id of the parent that can be hidden/shown
* class_parent (optional): The class of the parent if the display none is dynamically added with a class
If a class is not declared this control the display property.

### CODE REVIEW

**Comment by FiloSpaTeam** [comment]
Found another and better solution.
Removed the class_parent option.
I need only the id of the parent. With javascript i'll see if offsetWidth or offsetHeight are > 0.
If yes then i'll drawHandles ;-)
I think it can be a good solution now :+1:

**Comment by FiloSpaTeam** [comment]
sorry i remove this later, now i m out :)

**Comment by FiloSpaTeam** [comment]
Found new solution with jQuety closest.
But heavy (not 100%, 70-80%, one core) CPU use now is generated from jQuery control.
I'll try something later.

**Comment by FiloSpaTeam** [comment]
Later last update, the 100% for hidden sliders is solved, althought when slider is visible and there are 15/16 sliders the CPU go to 100%.

**Comment by IonDen** [comment]
Hello, @FiloSpaTeam.
I checked you request, and i can not accept it.
You didn't preserve the code style.

**Comment by FiloSpaTeam** [comment]
OK no problem :)
Help me to change to your style coding :+1:

**Comment by IonDen** [comment]
Shortened conditions, extra spaces. All this stuff.

**Comment by FiloSpaTeam** [comment]
I use VIM for writing and i Tabularize code for more readability.
I thinked that anyone should use the minimized file for inclusion.
For conditions and others i'll see :)

**Comment by IonDen** [comment]
No matter in what editor you are writing your code. But if you want to send a pull request, it should have the exact code style, as base file. "Readability" updates are not allowed.

**Comment by FiloSpaTeam** [comment]
Ok. Understanding.
So i close :+1:

**Pull request closed without merging**
