### PR TITLE
update init event name and add event when user grabs handle

### LINKED ISSUE #359: Add new callback onInit and change role of onStart
- onInit should be executed with plugin start
- onStart should be executed on first pointer action

### PR DESCRIPTION
**Pull request by gsouquet**
I have renamed `onStart` to `onInit`, and then changed the behaviour of `onStart` to trigger when the user changes the value of `from` and `to`.

I've updated the `readme.md` but someone still need to update the russian one. 
Also it's a bit unclear what the process is when we release a new version. (How do we generate the minified file, how to update the version number, ...) 

This resolve #359 

Hope that help!

### CODE REVIEW

**Comment by IonDen** [comment]
Hello, good idea.
1. I can't merge your PR, because i'm developing version 3.x now (55% done) and have no time to update all documentation and test this feature in 2.x
2. I will implement this **onInit** callback in 3.x

**Comment by gsouquet** [comment]
Do you have an ETA for the release of the version 3.x ?
If you need some help i'd be happy to give a hand when I have some time. 

Thanks

**Comment by IonDen** [comment]
No exact ETA for now. 1-2 weeks i think.

**Comment by IonDen** [comment]
Do you have an access to MS devices (Surface, Hybrid transformers on Windows, Win Mobiles)?

**Comment by gsouquet** [comment]
Unfortunately not, I mostly have access to Apple products

**Comment by gsouquet** [comment]
I'm closing this PR since it's never going to be merged

**Comment by IonDen** [comment]
Please create a feature request when.

**Pull request closed without merging**
