### PR TITLE
Improve big grid, by converting big ticks into small ticks

### PR DESCRIPTION
**Pull request by ncoquelet**
If there are a lot of big tick displayed on the grid, the layout can be very confusing.
http://jsfiddle.net/sbx6zcnm/1/

To improve that, I just changed a little the grid generation code, to convert the extra ticks into small ticks.

With that, there are much less labels in the grid, the label collision code works better and it's more clear for which label is associated with tick.

demo http://jsfiddle.net/sbx6zcnm/2/

### CODE REVIEW

**Comment by ncoquelet** [comment]
It still 2 bugs.

1. it can always have a lot of small ticks. we needs a way to limit it but in the same time, the small tick position must respect the step option.

2. there is a strange behavior in the last part of the grid. I think it's a different bug.
After look it, I don't understand the real intention of the line 2085 ?
```
2082                if (big_w > 100) {
2083                    big_w = 100;
2084
2085                    local_small_max -= 2;
2086                    if (local_small_max < 0) {
2087                        local_small_max = 0;
2088                    }
2089                }
```

Thanks

**Comment by ncoquelet** [comment]
I have fixed the point 2 :-)

**Comment by IonDen** [comment]
Hi, not bad.
1. There should be some limit, no need to respect grid_snap to absurd.
2. If i'm not mistaken this was some strange buggy hack. You should understand that my grid was a beta for a long time and i'm still looking forward to refactor it.

So you are finished with this PR, or want to fix point 1?

**Comment by IonDen** [comment]
Also, please remove sublime files from PR.

**Comment by ncoquelet** [comment]
Hi @IonDen,

Sorry for delay, i little bit busy last week.
For this PR, i want to try an other idea with more accuracy. 
Stay tuned ;-)

**Comment by IonDen** [comment]
@ncoquelet ok)

**Pull request closed without merging**
